# Generated by Django 4.0.6 on 2022-07-25 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_desc', models.TextField(max_length=500)),
                ('task_category', models.CharField(max_length=100)),
                ('task_assign_date', models.DateField(default=0, null=True)),
                ('task_end_date', models.DateField(default=0, null=True)),
                ('assigned_by', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=200)),
                ('is_removed', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 7, 25, 8, 29, 55, 438842))),
                ('updated_at', models.DateTimeField(blank=True, default=0, null=True)),
                ('removed_at', models.DateTimeField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'tbl_task',
            },
        ),
    ]
