# Generated by Django 4.0.6 on 2022-08-02 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todoapp', '0002_task_name_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='task_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 8, 23, 15, 106014)),
        ),
        migrations.AlterField(
            model_name='task',
            name='removed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 8, 23, 15, 106014), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 8, 23, 15, 106014), null=True),
        ),
    ]
